#!/bin/bash

# var 
red=$'\e[1;31m'
grn=$'\e[1;32m'
blu=$'\e[1;34m'
mag=$'\e[1;35m'
cyn=$'\e[1;36m'
white=$'\e[0m'

for i in $(vmware-hgfsclient); 
do 
	echo -ne " Mounting $blu $i $white on /media/vmware-share/$i .. "
	mkdir -p /media/vmware-share/$i 
	vmhgfs-fuse ".host:/$i" /media/vmware-share/$i 2>/dev/null
	if [ $? -eq 0 ]
	then
          echo " $grn [ok] $white"
	else
          echo " $red [nok] $white"
	fi
done

